import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const helvetica = localfont({
  src: [
    {
      path: "../fonts/helvetica.otf",
    },
  ],
  variable: "--font-helvetica",
});

const urbanist = localfont({
  src: [
    {
      path: "../fonts/Urbanist.ttf",
    },
  ],
  variable: "--font-urbanist",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${helvetica.variable} ${urbanist.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
